<<<<<<< HEAD
# Generated by Django 4.2 on 2023-12-27 13:07
=======
# Generated by Django 5.0 on 2023-12-21 17:36
>>>>>>> 5abe11fb1ad1bdfc29c2cecfb0bd62b92f70034d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='CurrencyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма в долларах')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс обмена')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
=======
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
>>>>>>> 5abe11fb1ad1bdfc29c2cecfb0bd62b92f70034d
            ],
        ),
    ]
